version: "3.3"
services:
  processor:
    image: linea-processor
    user: "${UID:-1000}:${GID:-1000}"
    tty: true
    stdin_open: true
    volumes:
      - "./data:/src/data"
      - "./incoming:/src/incoming"
      - "./data/videos:/src/videos"
      - "./www:/src/www"
    # environment:
    #   - LINEA_STREAMING_BASE_URL=https://tv.yourdomain
    #   - LINEA_VIDEOS_BASE_URL=https://ostorage.yourdomain

  web:
    image: sebp/lighttpd
    ports:
      - "8066:80"
    depends_on:
      processor:
        condition: service_completed_successfully
    volumes:
      - "./lighttpd/cache:/var/cache/lighttpd/compress"
      - "./lighttpd/config:/etc/lighttpd"
      - "./lighttpd/logs:/var/log/lighttpd"
      # Web Page
      - "./www/index.html:/var/www/localhost/htdocs/index.html"
      - "./www/index._hs:/var/www/localhost/htdocs/index._hs"
      - "./www/images:/var/www/localhost/htdocs/images"
      # Data
      - "./www/data.json:/var/www/localhost/htdocs/data.json"
      - "./data/covers:/var/www/localhost/htdocs/covers"
      - "./data/videos:/var/www/localhost/htdocs/videos"
    restart: no

    # networks:
    #   - traefik-network
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.services.tv.loadbalancer.server.port=80"
    #   # Router
    #   - "traefik.http.routers.tv.rule=Host(`tv.yourdomain`)"
    #   - "traefik.http.routers.tv.entrypoints=websecure"
    #   - "traefik.http.routers.tv.tls=true"
    #   - "traefik.http.routers.tv.tls.certresolver=letsencrypt"

networks:
  traefik-network:
    external: true
